services:
  nginx-react:
    container_name: nginxreact
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    environment:
      NODE_ENV: production
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro # I am using CertBot
    restart: always
